// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJC2WmvGIG6dZNC6ccoCTi7GqeYWEUvGc',
    appId: '1:783164352992:web:6098c2f659afad693f6385',
    messagingSenderId: '783164352992',
    projectId: 'food-mb',
    authDomain: 'food-mb.firebaseapp.com',
    storageBucket: 'food-mb.firebasestorage.app',
    measurementId: 'G-5M39LT7HQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkAQwyBqefpjwC0kTJIGKZ31FIkViKetc',
    appId: '1:783164352992:android:97a57dbb9137da1c3f6385',
    messagingSenderId: '783164352992',
    projectId: 'food-mb',
    storageBucket: 'food-mb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmtrL-eKy3mgcQwx1xZhS1qnuCFiiOBFU',
    appId: '1:783164352992:ios:f4aef3a0f092e39c3f6385',
    messagingSenderId: '783164352992',
    projectId: 'food-mb',
    storageBucket: 'food-mb.firebasestorage.app',
    iosBundleId: 'com.example.drinkApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmtrL-eKy3mgcQwx1xZhS1qnuCFiiOBFU',
    appId: '1:783164352992:ios:f4aef3a0f092e39c3f6385',
    messagingSenderId: '783164352992',
    projectId: 'food-mb',
    storageBucket: 'food-mb.firebasestorage.app',
    iosBundleId: 'com.example.drinkApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJC2WmvGIG6dZNC6ccoCTi7GqeYWEUvGc',
    appId: '1:783164352992:web:4def3ddef012e4583f6385',
    messagingSenderId: '783164352992',
    projectId: 'food-mb',
    authDomain: 'food-mb.firebaseapp.com',
    storageBucket: 'food-mb.firebasestorage.app',
    measurementId: 'G-47SQ2QN6B2',
  );
}
